### ISSUE TITLE
Gestion de l'état activeMenu

### ISSUE THREAD

**Issue by IannisG10** [branGitfox/Pro#1]
Pour la gestion de ton état activeMenu pense à utiliser fonction de gestion a part pour contrôler la mise à jour de ton état,car ça provoque un retard sur le rendu de la valeur
exemple :
  const handlerActiveMenu = ( ) => { 
           // Fonction de mise à jour de l'état 
           setActiveMenu(prevActiveMenu => 
               !prevActiveMenu);
  }
 En utilisant une fonction de rappel, tu pourras éviter les bugs lier à la mise à jour de ton état, surtout si tu prévois d'utiliser UseEffect

**Comment by branGitfox** [comment]
Okey je réviserai ça

**Comment by branGitfox** [comment]
Merci

**Comment by branGitfox** [comment]
gestion de l'etat fait
